### ISSUE TITLE
Colab zip extraction for Hateful Memes fails

### ISSUE THREAD

**Issue by jdsteen627** [facebookresearch/mmf#886]
## 🐛 Bug

The hateful memes notebook example fails due to issues with extracting the zip file. 
## To Reproduce

1. Open the example (https://colab.research.google.com/github/facebookresearch/mmf/blob/notebooks/notebooks/mmf_hm_example.ipynb)
2. Run the cells up to number 5
3. Running cell 5 as is leads to a checksum error
4. Adding --bypass_checksum=1 avoids checksum issue, but leads to "AssertionError: dev.jsonl doesn't exist in /root/.cache/torch/mmf/data/datasets/hateful_memes/defaults/images"
5. (some) later cells will work, but any requiring the extracted data fail with "AssertionError: Hateful Memes Dataset doesn't do automatic downloads; please follow instructions at https://fb.me/hm_prerequisites"

![failed_extraction](https://user-images.githubusercontent.com/52748802/115037627-ab3e3680-9e9c-11eb-9ab6-8b4c13adee77.png)
![failed_training](https://user-images.githubusercontent.com/52748802/115037638-ada09080-9e9c-11eb-8735-1488b9ee4d27.png)

**Comment by apsdehal** [comment]
We are looking into this. Thanks for pointing out the issue.

**Comment by apsdehal** [comment]
Hi,
Can you please install latest version of MMF using 

```
pip uninstall -y mmf
pip install mmf@https://github.com/facebookresearch/mmf/tarball/master
```

That should fix this issue.

**Comment by davkis123** [comment]
Still getting AssertionError: train.jsonl doesn't exist in /root/.cache/torch/mmf/data/datasets/hateful_memes/defaults/images #887

**Comment by Noman-Tanveer** [comment]
I'm also facing the same issue. I have a fresh install from the directory.

**Comment by woquinocoin** [comment]
> I'm also facing the same issue. I have a fresh install from the directory.

I found that it is because the mmf_convert method added /data to the path while unzipping. Hence, the structure of the zip file should look like hateful_memes/data/img or ateful_memes/data/test.jsonl
Here is their source code about the path:

`for file in files_needed:`
`exists = exists or PathManager.exists(os.path.join(folder, "data", file))`

**Comment by lmwijesundara** [comment]
I'm having the same issue. @woquinocoin is this worked?

**Comment by lmwijesundara** [comment]
I rearranged and compressed as mentioned, but didn't work for me

**Comment by mingshanhee** [comment]
Thanks @Noman-Tanveer! Your solution worked for me. They probably changed the directory name containing the data without making modifications to the cli methods.

**Comment by woquinocoin** [comment]
> I rearranged and compressed as mentioned, but didn't work for me

try to use this dataset I re-ziped: https://drive.google.com/file/d/1qkp3G7Ua_ePz1tBKI6tF2tjCqf6_O2d-/view?usp=sharing

**Comment by AnjumJ123** [comment]
> Still getting AssertionError: train.jsonl doesn't exist in /root/.cache/torch/mmf/data/datasets/hateful_memes/defaults/images #887

I am getting the same issue. Even though train.jsonl is in the path /root/.cache/torch/mmf/data/datasets/hateful_memes/defaults/images, the system is failing the assertion. Any help or suggestion to solve the issue will be appreciated.

**Comment by Hao-YunDeng** [comment]
I'm having the same issue. Waiting for solutions

**Comment by karembadawy** [comment]
@AnjumJ123  @Hao-YunDeng Try to unzip the file then compress it again after renaming the folder from `hateful_memes` to `data` this works for me.

**Comment by DanielLin97** [comment]
> > I rearranged and compressed as mentioned, but didn't work for me
> 
> try to use this dataset I re-ziped: https://drive.google.com/file/d/1qkp3G7Ua_ePz1tBKI6tF2tjCqf6_O2d-/view?usp=sharing

sorry the link does not work now. Could you please share me with the dataset? I need the images in the dataset. I promise to only use it for research purposes and will not distribute it to any third parties.

**Comment by Eryk1705** [comment]
#1308

**Comment by himi11** [comment]
> > Still getting AssertionError: train.jsonl doesn't exist in /root/.cache/torch/mmf/data/datasets/hateful_memes/defaults/images #887
> 
> I am getting the same issue. Even though train.jsonl is in the path /root/.cache/torch/mmf/data/datasets/hateful_memes/defaults/images, the system is failing the assertion. Any help or suggestion to solve the issue will be appreciated.

were you able to fix it? I'm facing the same issue.

**Comment by mr-rhombus** [comment]
> > > Still getting AssertionError: train.jsonl doesn't exist in /root/.cache/torch/mmf/data/datasets/hateful_memes/defaults/images #887
> > 
> > 
> > I am getting the same issue. Even though train.jsonl is in the path /root/.cache/torch/mmf/data/datasets/hateful_memes/defaults/images, the system is failing the assertion. Any help or suggestion to solve the issue will be appreciated.
> 
> @AnjumJ123 were you able to fix it? I'm facing the same issue.

I was battling through these same issues last night. This is what worked for me.

0. Download hateful memes data from [here](https://hatefulmemeschallenge.com/)
1. Unzip "hateful_memes.zip"
2. Rename "hateful_memes" dir to "data"
3. Re-zip "data" dir to "data.zip"
4. Run `mmf_convert_hm --zip_file=data.zip --password=password --bypass_checksum=1` to "mmf-ify" the data (per the "Prerequisites" section [here](https://github.com/facebookresearch/mmf/blob/main/projects/hateful_memes/README.md#prerequisites))

FWIW, I'm on a PC and using `mmf=1.0.0rc12`. I installed `mmf` according to the [mmf docs](https://mmf.sh/docs/), specifically with the `pip install --editable .` option (which came with its own set of challenges)
